services:
  db:
    image: mysql:latest
    ports:
      - 5905:3306
    volumes:
      - ./db_data:/var/lib/mysql
    env_file: .db.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 5321:80
    depends_on:
      - db
    env_file: .db.env

volumes:
  my-db-volume: